name: SmartUI SDK Cloud GitHub Actions - Monorepo

on:
  workflow_dispatch:
    inputs:
      project_token_1:
        description: Project Token - 1
        required: true
      project_token_2:
        description: Project Token - 2
        required: true

env:
  LT_USERNAME: ${{ secrets.LT_USERNAME }}
  LT_ACCESS_KEY: ${{ secrets.LT_ACCESS_KEY }}

jobs:
  smartui_tests:
    name: Execute SmartUI SDK Cloud Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm i @lambdatest/smartui-cli

      - name: Execute Java-TestNG-SmartUI tests
        env:
          PROJECT_TOKEN: ${{ github.event.inputs.project_token_1 }}
        run: |
          npx smartui --version
          npx smartui config:create smartui-web.json
          npx smartui --config smartui-web.json exec -- mvn --quiet test -D suite=sdk-cloud.xml

      - name: Execute Java-TestNG-SmartUI SmartUI tests
        env:
          PROJECT_TOKEN: ${{ github.event.inputs.project_token_2 }}
        run: |
          npx smartui --version
          npx smartui config:create smartui-web.json
          npx smartui --config smartui-web.json exec -- mvn --quiet test -D suite=sdk-cloud.xml
